security:
    encoders:
        App\Entity\Usersite:
            algorithm: '%encoder_algorithm%'

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usersite
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                username_parameter: login[emailCanonical]
                password_parameter: login[password]
                always_use_default_target_path: true
                default_target_path: /
            logout:
                path: logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2629746 # 1 month
                path: /

    access_control:
        - { path: ^/user/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
