production:
    stage: deploy
    script:
    - sudo -u root rsync / /var/www/account-manager/ --exclude="vendor" --exclude="node_modules" --exclude="var" -exclude=".gitlab-ci.yml"
    - cd /var/www/account-manager
    - sudo -u www-data composer install
    - sudo -u www-data cp /var/env-projects/account-manager ./.env
    - sudo -u www-data php ./bin/console ca:c
    - sudo -u www-data php ./bin/console ca:warmup
    - sudo -u www-data yarn encore production
    when: manual
    only:
    - production