production:
    stage: deploy
    script:
    - sudo -u www-data composer install
    - sudo -u www-data cp /var/env-projects/account-manager ./.env
    - sudo -u www-data php ./bin/console ca:c
    - sudo -u www-data php ./bin/console ca:warmup
    - sudo -u www-data yarn encore production
    when: manual
    only:
    - production