production:
    stage: deploy
    script:
        - sudo -u root rsync -rz * /var/www/account-manager/ --exclude="vendor" --exclude="node_modules" --exclude="var" -exclude=".gitlab-ci.yml"
        - cd /var/www/account-manager
        - sudo -u root chown www-data:www-data -R ./*
        - sudo -u www-data composer install
        - sudo -u www-data cp /var/env-projects/account-manager ./.env
        - sudo -u www-data php ./bin/console ca:c
        - sudo -u www-data php ./bin/console ca:warmup
        - sudo -u www-data yarn encore production
    when: manual
    environment:
        name: production
        url: https://account-manager.webcoder01.com
    only:
        - production