# Index
index:
    path: /
    controller: App\Controller\IndexController::index

# Security
login:
    path: /user/login
    controller: App\Controller\SecurityController::login

logout:
    path: /user/logout
    methods: [GET]

reset_request:
    path: /user/reset
    controller: App\Controller\SecurityController::resetRequest

reset_password:
    path: /user/reset/{token}
    controller: App\Controller\SecurityController::resetPassword
    requirements:
        token: '[0-9A-Za-z]+'

# Account
account.view:
    path: /account/{year}/{month}/{id}
    controller: App\Controller\AccountController:view
    defaults:
        id: 0
    requirements:
        year: '\d{4}'
        month: '\d{1,2}'
        id: '\d+'

account.add:
    path: /account/add
    controller: App\Controller\AccountController:add
    methods: [POST]

# Operation
operation.add:
    path: /{type}/add
    controller: App\Controller\OperationController:add
    defaults:
        type: transaction
    requirements:
        type: '(transaction|income|budget)'
        
operation.edit:
    path: /{type}/edit/{id}
    controller: App\Controller\OperationController:edit
    requirements:
        type: '(transaction|income|budget)'
        id: '\d+'

operation.delete:
    path: /{type}/delete/{id}
    controller: App\Controller\OperationController:delete
    requirements:
        type: '(transaction|income|budget)'
        id: '\d+'

# Budget
budget.view:
    path: account/budget
    controller: App\Controller\BudgetController:view
    
budget.manage:
    path: account/budget/{id}
    controller: App\Controller\BudgetController:manage
    requirements:
        id: '\d+'
